### Login
POST http://localhost:8000/login
Content-Type: application/json

{
	"email": "anyone@unknown.spy",
	"password": "11111"
}

### Register
POST http://localhost:8000/register
Content-Type: application/json

{
	"firstName": "john",
	"lastName": "doe",
	"email": "anyone@unknown.spy",
	"password": "11111"
}

### Register admin
POST http://localhost:8000/registerAdmin
Content-Type: application/json

{
	"firstName": "rooty",
	"lastName": "root",
	"email": "ro@ot.adm",
	"password": "11111",
	"rootPassword": "murloc_power"
}

### Logout
POST http://localhost:8000/logout
Content-Type: application/json
