### Get all users FOR USERS WITH ISADMIN = TRUE
GET http://localhost:8000/getAll
Content-Type: application/json

### Get one user FOR USERS WITH ISADMIN = TRUE
GET  http://localhost:8000/getOne/19
Content-Type: application/json

### Update
PATCH http://localhost:8000/update
Content-Type: application/json

{
	"firstName": "qweqwe",
	"lastName": "qwewqe",
	"email": "qweqwe@qwe.qwe",
	"password": "11111"
}

### Update any user FOR USERS WITH ISADMIN = TRUE
PATCH http://localhost:8000/updateAny
Content-Type: application/json

{
	"firstName": "qweqwe",
	"lastName": "qwewqe",
	"email": "qweqwe@qwe.qwe",
	"password": "11111",
	"isAdmin": true,
	"updateId": 19
}

### Delete
DELETE http://localhost:8000/delete
Content-Type: application/json

### Delete any user FOR USERS WITH ISADMIN = TRUE
DELETE http://localhost:8000/deleteAny
Content-Type: application/json

{
	"deleteId": 19
}